import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@pollar/react/styles.css";
import { PollarProvider } from "@pollar/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <PollarProvider
          client={{ apiKey: process.env.NEXT_PUBLIC_POLLAR_API_KEY!, stellarNetwork: "testnet" }}
        >
          {children}
        </PollarProvider>
      </body>
    </html>
  );
}
